<?php
/** @var \VladZahorodnii\HomeCategory\Block\HomeCategories $block */

$allCategories = $block->getCategories();
?>

<div class="categories-container">
    <?php foreach ($allCategories as $category): ?>
        <ul class="category-list">
            <li class="category-item">
                <a href="<?= $category['url'] ?>"><?= $category['name'] ?></a>
            </li>
        </ul>
    <?php endforeach; ?>
</div>

